[tool.poetry]
name = "Flask Blueprint Tutorial"
version = "0.1.0"
description = ""
authors = ["Todd Birchard <toddbirchard@gmail.com>"]
maintainers = ["Todd Birchard <toddbirchard@gmail.com>"]
license = "MIT"
readme = "README.md"
homepage = "https://hackersandslackers.com/flask-blueprints/"
repository = "https://github.com/hackersandslackers/flask-blueprint-tutorial/"
documentation = "https://hackersandslackers.com/flask-blueprints/"
keywords = ["Flask",
            "Blueprints",
            "Framework",
            "App",
            "Tutorial"]

[tool.poetry.dependencies]
python = "^3.8"
flask = "*"
flask-assets = "*"
python-dotenv = "*"

[tool.poetry.dev-dependencies]
lesscpy = "*"
cssmin = "*"
jsmin = "*"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"

[tool.poetry.scripts]
run = "wsgi:app"

[tool.poetry.urls]
issues = "https://github.com/hackersandslackers/flask-blueprint-tutorial/issues"
